# configuration k:v                     # envvar override    # usage
verbose_logs = false                    # P4U_VERBOSE        # enable to get verbose logs emitted next to p4d/p4s
case_sensitive = false                  # P4U_CASE_SENSITIVE # when matching file paths, set to TRUE to only do a precice case match
perforce_server = "localhost:1666"      # P4U_SERVER         # p4 port to use
perforce_user = "user"                  # P4U_USER           # user to login
perforce_pass = "pwd"                   # P4U_PASS           # pass / token to use for user login
bypass_keyphrase = "p4unity-bypass"     # P4U_BYPASS         # 

# list of path prefixes to check 
# eg. "//" or "//<your_depot>/" means every commit is going to be checked
#     "//MyDepot/UnityProjects/" could filter it down to just the unity folder, for example
#
path_whitelist = [ "//" ]